version: 2

models:
    - name: fact_order
      description: "Tabela de Fatos"
      columns:
          - name: order_id
            description: "A chave primária original da tabela"
            tests:
                - unique
                - not_null
    - name: dim_customers
      description: "Dimensão dos Clientes"
      columns:
          - name: customer_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_product
      description: "Dimensão dos Produtos"
      columns:
          - name: product_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_shipper
      description: "Dimensão das Transportadoras"
      columns:
          - name: shipper_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_supplier
      description: "Dimensão dos Fornecedores"
      columns:
          - name: supplier_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_employees
      description: "Dimensão dos Empregados"
      columns:
          - name: employee_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_order_details
      description: "Dimensão dos Detalhes da Ordem"
      columns:
          - name: order_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null